---
# This playbook sets up whole stack.
- hosts: tag_Name_MSR_test_Instance_2
  remote_user: ubuntu # Remote user
  become: yes
  tasks:
    - name: Clone a private repository into ~/docker-ansible.
      git:
        repo: 'https://github.com/venkat09docs/docker-ansible.git'
        version: master
        dest: /opt/docker-ansible
    - name: This command will execute the shell
      shell: docker-compose up -d >> output.txt
      args:
        chdir: /opt/docker-ansible/couchdb/  
